version: '3.7'

services:
  php_telnet_teste:
    image: "php-local:1.1"
    tty: true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '8082:80'
  #    - '8232:8232'
    volumes:
      - ./:/var/www/html
      - ./log:/var/log/suporte4
#    entrypoint:
#      "php -S 0.0.0.0:8232 /var/www/html/public/index.php"
